set_vane_horizontal:
  target:
    entity:
      integration: melcloud
      domain: climate
  fields:
    position:
      required: true
      example: "auto"
      selector:
        text:

set_vane_vertical:
  target:
    entity:
      integration: melcloud
      domain: climate
  fields:
    position:
      required: true
      example: "auto"
      selector:
        text:

set_atw_power:
  fields:
    device_name:
      required: true
      example:
        - Casa
        - Agrinido
      selector:
        object:
    power:
      required: true
      example: true
      selector:
        boolean:
